version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    deploy:
      placement:
        constraints:
          - node.role==manager
        max_replicas_per_node: 1
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: integer
      POSTGRES_USER: inti
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "integer", "-U", "inti"]
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped
    secrets:
      - postgres_password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:

secrets:
  postgres_password:
    file: ./db/password.txt

volumes:
  postgres_data:

