version: "3.9"

services:
  api:
    image: integer_api
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: integer
      DB_USER: inti
      DB_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - backend
    restart: unless-stopped
    secrets:
      - db_password

  db:
    image: postgres:13-alpine
    deploy:
      placement:
        constraints:
          - node.role==manager
        max_replicas_per_node: 1
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: integer
      POSTGRES_USER: inti
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "integer", "-U", "inti"]
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped
    secrets:
      - db_password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data

networks:
  backend:

secrets:
  db_password:
    file: ./db/password.txt

volumes:
  db_data:

